apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - image: wordpress
        name: wordpress
        env:
        - name: WORDPRESS_DB_HOST
          value: mysql-service
        - name: WORDPRESS_DB_NAME
          value: wp_db
        - name:  WORDPRESS_DB_USER
          value: gerold
        - name: WORDPRESS_DB_PASSWORD
          value: gerold
        ports:
        - containerPort: 80
          name: wordpress
        volumeMounts:
        - name: data-wp
          mountPath: /var/www/html
      volumes:
      - name: data-wp
        hostPath:
          # chemin du dossier sur l hote
          path: /data
          # ce champ est optionel
          type: Directory
